name: dbt_project
profile: milleetunmots
version: 1.0.0
config-version: 2

docs-paths: ["docs"]
snapshot-paths: ["snapshots"]

quoting:
  # https://docs.getdbt.com/reference/project-configs/quoting
  database: false
  schema: false
  identifier: false

vars:
  daily_company_start_date: to_date('2022/01/01', 'yyyy/mm/dd') # Company daily table start date

tests:
  +store_failures: true

snapshots:
  +target_schema: snapshots

seeds:
  +delimiter: ";"
  +schema: seed


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.

models:
  +transient: false
  materialized: table
  dbt_project:
    analytics:
      schema: analytics
    dim:
      schema: dim
    fact:
      schema: fact
    staging:
      schema: staging
    seed:
      schema: seed
    tests:
      schema: tests
