# example profiles.yml file
milleetunmots:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: APHZCUS-WH41832
      user: DBT_PROD_USER
      role: DBT_PROD_ROLE
      password: 6TX4A#Vk4iNfe9g
      database: MOTS_DW
      warehouse: COMPUTE_WH
      schema: public
      threads: 200
      # Paramètres de connexion supplémentaires pour la robustesse
      client_session_keep_alive: true
      connection_timeout: 60
      retry_on_database_errors: true
      retry_allowed: 3