with source as (
    select *
    from {{ source('seed', 'seed_super_table') }}
)

select
    concat(family_id, '_', child_id) as ind,
    family_id,
    child_id,
    null as support_creation_date,
    gender,
    null as birthdate,
    age_today_in_months,
    age_range_at_start_of_cohort,
    group_status,
    null as end_of_active_status,
    number_of_children,
    is_desengage_T2,
    is_estime_desengage_T2,
    is_desengage_T1,
    is_estime_desengage_T1_conserve,
    is_estime_desengage_T1,
    is_estime_desengage_T2_conserve,
    engagement_state_t1,
    engagement_state_t2,
    parent1_city_name,
    source_name,
    source_channel,
    source_department,
    parent1_postal_code,
    departement,
    parent1_degree,
    cohort_name,
    supporter_name, 
    trim(rtrim(call_0_status)) as call_0_status,
    trim(rtrim(call1_status)) as call1_status,
    trim(rtrim(call2_status)) as call2_status,
    trim(rtrim(call3_status)) as call3_status,
    call1_previous_goals_follow_up,
    call2_previous_goals_follow_up,
    call4_previous_goals_follow_up,
    is_call0_goals,
    is_call1_goals,
    is_call2_goals,
    is_call3_goals,
    is_call0_status,
    is_call1_status,
    is_call2_status,
    is_call3_status,
    number_of_calls,
    call_0_duration,
    call1_duration,
    call2_duration,
    call3_duration,
    review_call0,
    review_call1,
    review_call2,
    review_call3,
    nb_of_tries_call0,
    nb_of_tries_call1,
    nb_of_tries_call2,
    nb_of_tries_call3,
    mid_term_rate,
    mid_term_reaction,
    module2_name,
    module3_name,
    module4_name,
    module5_name,
    module6_name, 
    is_bilingue,
    registration_delay,
    age_at_registration,
    tag_list,
    is_excluded_from_analytics,
    is_call_0_1_status_OK
from source
